version: "3.8"

services:
  numbergame:
    build:
      context: .
      dockerfile: Dockerfile
    image: akashtiwari05/number-guessing-game:prod
    container_name: numbergame-container
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
      # Optional: force CLI to run in non-interactive env if you implement PLAY_CLI check in code
      # - PLAY_CLI=true
    restart: "no"
